import { UserCircleIcon, WrenchIcon, TruckIcon, ShoppingBagIcon, BuildingOfficeIcon, HomeIcon, CodeBracketIcon, BriefcaseIcon, UserGroupIcon } from '@heroicons/react/24/outline'
import { WrenchScrewdriverIcon, TruckIcon as TruckSolidIcon, ShoppingBagIcon as ShoppingSolidIcon, BuildingOfficeIcon as OfficeSolidIcon, HomeIcon as HomeSolidIcon, CodeBracketIcon as CodeSolidIcon, BriefcaseIcon as BriefcaseSolidIcon, UserGroupIcon as UsersSolidIcon } from '@heroicons/react/24/solid'

export const SERVICE_CATEGORIES = [
  { label: 'Electrician', value: 'Electrician', icon: WrenchScrewdriverIcon },
  { label: 'Plumber', value: 'Plumber', icon: WrenchIcon },
  { label: 'Carpenter', value: 'Carpenter', icon: WrenchIcon },
  { label: 'Mason', value: 'Mason', icon: BuildingOfficeIcon },
  { label: 'Painter', value: 'Painter', icon: WrenchIcon },
  { label: 'AC Repair', value: 'AC Repair', icon: WrenchScrewdriverIcon },
  { label: 'Washing Machine', value: 'Washing Machine Repair', icon: HomeIcon },
  { label: 'Refrigerator', value: 'Refrigerator Repair', icon: HomeIcon },
  { label: 'RO Purifier', value: 'RO Water Purifier Service', icon: WrenchIcon },
  { label: 'Home Cleaning', value: 'Home Cleaning', icon: HomeIcon },
  { label: 'Pest Control', value: 'Pest Control', icon: WrenchIcon },
  { label: 'Appliance Repair', value: 'Appliance Repair', icon: WrenchScrewdriverIcon },
  { label: 'Mobile Repair', value: 'Mobile Repair', icon: CodeBracketIcon },
  { label: 'Laptop Repair', value: 'Computer/Laptop Repair', icon: CodeBracketIcon },
  { label: 'Delivery Service', value: 'Delivery Services', icon: TruckIcon },
  { label: 'Driver Service', value: 'Driver Services', icon: TruckIcon },
  { label: 'Security Guard', value: 'Security Guard', icon: UserGroupIcon },
  { label: 'Housekeeping', value: 'Housekeeping', icon: HomeIcon },
  { label: 'Salon at Home', value: 'Salon at Home', icon: UserGroupIcon },
  { label: 'Tailor', value: 'Tailor Services', icon: ShoppingBagIcon },
]

export const dummyWorkers = [
  { id: 'w1', name: 'Rajesh Kumar', email: 'rajesh@example.com', phone: '+91 98765 43210', category: 'Plumber', services: ['Plumber', 'Pipe Fitting'], location: 'Lajpat Nagar, Delhi', bio: 'Experienced plumber with 8+ years. Specializing in residential and commercial plumbing solutions.', rating: 4.8, total_reviews: 124, experience_years: 8, completion_rate: 97, availability: true, lat: 28.5700, lng: 77.2400, hourly_rate: 500, user_type: 'worker', avatar_color: 'bg-blue-500' },
  { id: 'w2', name: 'Priya Singh', email: 'priya@example.com', phone: '+91 98765 43211', category: 'Home Cleaning', services: ['Home Cleaning', 'Deep Cleaning', 'Office Cleaning'], location: 'Connaught Place, Delhi', bio: 'Professional cleaner providing spotless results. Eco-friendly products used.', rating: 4.9, total_reviews: 89, experience_years: 5, completion_rate: 99, availability: true, lat: 28.6315, lng: 77.2167, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-pink-500' },
  { id: 'w3', name: 'Amar Patel', email: 'amar@example.com', phone: '+91 98765 43212', category: 'Electrician', services: ['Electrician', 'Wiring', 'AC Repair'], location: 'Karol Bagh, Delhi', bio: 'Licensed electrician. Expert in wiring, switchboard installation, and AC servicing.', rating: 4.7, total_reviews: 156, experience_years: 10, completion_rate: 95, availability: true, lat: 28.6514, lng: 77.1907, hourly_rate: 600, user_type: 'worker', avatar_color: 'bg-yellow-500' },
  { id: 'w4', name: 'Sunita Devi', email: 'sunita@example.com', phone: '+91 98765 43213', category: 'Painter', services: ['Painter', 'Wall Art', 'Texture Painting'], location: 'Rajouri Garden, Delhi', bio: 'Creative painter with modern techniques. Interior and exterior painting specialist.', rating: 4.6, total_reviews: 67, experience_years: 6, completion_rate: 93, availability: true, lat: 28.6492, lng: 77.1219, hourly_rate: 550, user_type: 'worker', avatar_color: 'bg-purple-500' },
  { id: 'w5', name: 'Vikram Choudhary', email: 'vikram@example.com', phone: '+91 98765 43214', category: 'Carpenter', services: ['Carpenter', 'Furniture Repair', 'Wood Work'], location: 'Dwarka, Delhi', bio: 'Skilled carpenter specializing in custom furniture and repair work.', rating: 4.5, total_reviews: 98, experience_years: 12, completion_rate: 96, availability: true, lat: 28.5921, lng: 77.0460, hourly_rate: 700, user_type: 'worker', avatar_color: 'bg-orange-500' },
  { id: 'w6', name: 'Meena Kumari', email: 'meena@example.com', phone: '+91 98765 43215', category: 'Housekeeping', services: ['Housekeeping', 'Home Cleaning', 'Gardening'], location: 'Hauz Khas, Delhi', bio: 'Professional housekeeper. Deep cleaning, lawn maintenance, and indoor plant care.', rating: 4.8, total_reviews: 45, experience_years: 4, completion_rate: 98, availability: true, lat: 28.5494, lng: 77.2001, hourly_rate: 350, user_type: 'worker', avatar_color: 'bg-green-500' },
  { id: 'w7', name: 'Arjun Reddy', email: 'arjun@example.com', phone: '+91 98765 43216', category: 'AC Repair', services: ['AC Repair', 'Refrigerator Repair', 'Appliance Repair'], location: 'Saket, Delhi', bio: 'Certified HVAC technician. All brands of AC, fridge, and cooling systems.', rating: 4.7, total_reviews: 112, experience_years: 7, completion_rate: 96, availability: true, lat: 28.5245, lng: 77.2066, hourly_rate: 650, user_type: 'worker', avatar_color: 'bg-cyan-500' },
  { id: 'w8', name: 'Fatima Khan', email: 'fatima@example.com', phone: '+91 98765 43217', category: 'Salon at Home', services: ['Salon at Home', 'Bridal Makeup', 'Hair Styling'], location: 'Khan Market, Delhi', bio: 'Professional beautician offering salon services at your doorstep. Bridal packages available.', rating: 4.9, total_reviews: 78, experience_years: 6, completion_rate: 99, availability: true, lat: 28.6003, lng: 77.2274, hourly_rate: 800, user_type: 'worker', avatar_color: 'bg-rose-500' },
  { id: 'w9', name: 'Suresh Yadav', email: 'suresh@example.com', phone: '+91 98765 43218', category: 'Mason', services: ['Mason', 'Tile Work', 'Waterproofing'], location: 'Rohini, Delhi', bio: 'Expert mason with specialization in tile fitting, plastering, and waterproofing solutions.', rating: 4.4, total_reviews: 86, experience_years: 9, completion_rate: 92, availability: true, lat: 28.7495, lng: 77.0565, hourly_rate: 600, user_type: 'worker', avatar_color: 'bg-amber-600' },
  { id: 'w10', name: 'Kavitha Nair', email: 'kavitha@example.com', phone: '+91 98765 43219', category: 'Pest Control', services: ['Pest Control', 'Termite Treatment', 'Fumigation'], location: 'Defence Colony, Delhi', bio: 'Licensed pest control specialist. Safe, eco-friendly treatments for homes and offices.', rating: 4.6, total_reviews: 54, experience_years: 5, completion_rate: 97, availability: true, lat: 28.5742, lng: 77.2340, hourly_rate: 500, user_type: 'worker', avatar_color: 'bg-lime-600' },
  { id: 'w11', name: 'Rohit Sharma', email: 'rohit@example.com', phone: '+91 98765 43220', category: 'Mobile Repair', services: ['Mobile Repair', 'Screen Replacement', 'Software Fix'], location: 'Chandni Chowk, Delhi', bio: 'Mobile phone repair expert. All brands - Apple, Samsung, OnePlus, Xiaomi and more.', rating: 4.5, total_reviews: 132, experience_years: 4, completion_rate: 94, availability: true, lat: 28.6562, lng: 77.2302, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-indigo-500' },
  { id: 'w12', name: 'Deepak Mishra', email: 'deepak@example.com', phone: '+91 98765 43221', category: 'Computer/Laptop Repair', services: ['Computer/Laptop Repair', 'Networking', 'Data Recovery'], location: 'Noida Sector 62', bio: 'IT hardware specialist. Laptop repair, OS installation, virus removal, and data recovery.', rating: 4.7, total_reviews: 91, experience_years: 8, completion_rate: 95, availability: true, lat: 28.6270, lng: 77.3653, hourly_rate: 550, user_type: 'worker', avatar_color: 'bg-violet-500' },
  { id: 'w13', name: 'Ramesh Gupta', email: 'ramesh@example.com', phone: '+91 98765 43222', category: 'Driver Services', services: ['Driver Services', 'Outstation Trips', 'Airport Transfer'], location: 'Rajiv Chowk, Delhi', bio: 'Professional driver with commercial license. City rides, airport transfers, and outstation trips.', rating: 4.3, total_reviews: 64, experience_years: 10, completion_rate: 91, availability: true, lat: 28.6328, lng: 77.2197, hourly_rate: 350, user_type: 'worker', avatar_color: 'bg-teal-500' },
  { id: 'w14', name: 'Anita Joshi', email: 'anita@example.com', phone: '+91 98765 43223', category: 'Tailor Services', services: ['Tailor Services', 'Alterations', 'Custom Stitching'], location: 'Chittaranjan Park, Delhi', bio: 'Expert tailor for men and women. Blouse stitching, alterations, and custom outfits.', rating: 4.8, total_reviews: 76, experience_years: 10, completion_rate: 98, availability: true, lat: 28.5388, lng: 77.2479, hourly_rate: 450, user_type: 'worker', avatar_color: 'bg-fuchsia-500' },
  { id: 'w15', name: 'Manoj Tiwari', email: 'manoj@example.com', phone: '+91 98765 43224', category: 'Washing Machine Repair', services: ['Washing Machine Repair', 'Appliance Repair'], location: 'Noida Sector 15', bio: 'Washing machine specialist - front load, top load, semi-automatic. All major brands.', rating: 4.4, total_reviews: 58, experience_years: 5, completion_rate: 93, availability: true, lat: 28.5836, lng: 77.3100, hourly_rate: 450, user_type: 'worker', avatar_color: 'bg-sky-500' },
  { id: 'w16', name: 'Sanjay Verma', email: 'sanjay@example.com', phone: '+91 98765 43225', category: 'RO Water Purifier Service', services: ['RO Water Purifier Service', 'Water Testing'], location: 'Barakhamba Road, Delhi', bio: 'RO purifier installation, repair, and annual maintenance. All brands serviced.', rating: 4.5, total_reviews: 42, experience_years: 3, completion_rate: 95, availability: true, lat: 28.6340, lng: 77.2280, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-blue-400' },
  { id: 'w17', name: 'Prakash Raj', email: 'prakash@example.com', phone: '+91 98765 43226', category: 'Security Guard', services: ['Security Guard', 'CCTV Monitoring'], location: 'Gurgaon Cyber City', bio: 'Former military personnel. Professional security services for events, offices, and residences.', rating: 4.6, total_reviews: 38, experience_years: 8, completion_rate: 99, availability: true, lat: 28.4949, lng: 77.0882, hourly_rate: 300, user_type: 'worker', avatar_color: 'bg-slate-600' },
  { id: 'w18', name: 'Pooja Bansal', email: 'pooja@example.com', phone: '+91 98765 43227', category: 'Delivery Services', services: ['Delivery Services', 'Courier', 'Parcel Handling'], location: 'Golf Course Road, Gurgaon', bio: 'Reliable same-day delivery and courier services within Delhi NCR. Fragile items handled with care.', rating: 4.3, total_reviews: 49, experience_years: 2, completion_rate: 96, availability: true, lat: 28.4595, lng: 77.1025, hourly_rate: 250, user_type: 'worker', avatar_color: 'bg-orange-400' },
  { id: 'w19', name: 'Vijay Malhotra', email: 'vijay@example.com', phone: '+91 98765 43228', category: 'Electrician', services: ['Electrician', 'Generator Repair', 'Solar Installation'], location: 'Paharganj, Delhi', bio: 'Master electrician with expertise in generators and solar panel installation.', rating: 4.6, total_reviews: 72, experience_years: 12, completion_rate: 94, availability: true, lat: 28.6448, lng: 77.2165, hourly_rate: 700, user_type: 'worker', avatar_color: 'bg-red-500' },
  { id: 'w20', name: 'Neha Agarwal', email: 'neha@example.com', phone: '+91 98765 43229', category: 'AC Repair', services: ['AC Repair', 'Ventilation', 'Air Quality'], location: 'Mayur Vihar, Delhi', bio: 'Specialized in central AC systems, air quality improvement, and ventilation solutions.', rating: 4.8, total_reviews: 58, experience_years: 6, completion_rate: 97, availability: true, lat: 28.5939, lng: 77.2978, hourly_rate: 600, user_type: 'worker', avatar_color: 'bg-emerald-500' },
  { id: 'w21', name: 'Gaurav Saxena', email: 'gaurav@example.com', phone: '+91 98765 43230', category: 'Plumber', services: ['Plumber', 'Bathroom Fitting', 'Sanitary'], location: 'Vasundhara, Ghaziabad', bio: 'Expert bathroom renovation and sanitary fitting specialist. All modern fixtures.', rating: 4.5, total_reviews: 83, experience_years: 7, completion_rate: 95, availability: true, lat: 28.5211, lng: 77.3855, hourly_rate: 550, user_type: 'worker', avatar_color: 'bg-sky-400' },
  { id: 'w22', name: 'Preeti Gupta', email: 'preeti@example.com', phone: '+91 98765 43231', category: 'Salon at Home', services: ['Salon at Home', 'Hair Coloring', 'Keratin Treatment'], location: 'Greater Kailash, Delhi', bio: 'Celebrity hairstylist offering advanced hair treatments at home.', rating: 4.9, total_reviews: 112, experience_years: 9, completion_rate: 99, availability: true, lat: 28.5436, lng: 77.2361, hourly_rate: 1200, user_type: 'worker', avatar_color: 'bg-pink-400' },
  { id: 'w23', name: 'Ravi Teja', email: 'ravi@example.com', phone: '+91 98765 43232', category: 'Mobile Repair', services: ['Mobile Repair', 'Tablet Repair', 'Accessories'], location: 'Lajpat Nagar, Delhi', bio: 'Expert in smartphones, tablets, and all mobile accessories. Quick screen replacements.', rating: 4.4, total_reviews: 95, experience_years: 5, completion_rate: 92, availability: true, lat: 28.5667, lng: 77.2432, hourly_rate: 350, user_type: 'worker', avatar_color: 'bg-indigo-400' },
  { id: 'w24', name: 'Suman Lata', email: 'suman@example.com', phone: '+91 98765 43233', category: 'Tailor Services', services: ['Tailor Services', 'Designer Outfits', 'Bridal'], location: 'Shahdara, Delhi', bio: 'Master tailor specializing in bridal wear and designer ethnic outfits.', rating: 4.7, total_reviews: 64, experience_years: 15, completion_rate: 98, availability: true, lat: 28.6769, lng: 77.2927, hourly_rate: 600, user_type: 'worker', avatar_color: 'bg-rose-400' },
  { id: 'w25', name: 'Ajay Kumar', email: 'ajay@example.com', phone: '+91 98765 43234', category: 'Pest Control', services: ['Pest Control', 'Rodent Control', ' Fumigation'], location: 'Pitampura, Delhi', bio: 'Professional pest management for residential and commercial properties.', rating: 4.5, total_reviews: 47, experience_years: 6, completion_rate: 96, availability: true, lat: 28.7012, lng: 77.1376, hourly_rate: 450, user_type: 'worker', avatar_color: 'bg-lime-500' },
  { id: 'w26', name: 'Kiran Bedi', email: 'kiran@example.com', phone: '+91 98765 43235', category: 'Housekeeping', services: ['Housekeeping', 'Elder Care', 'Cooking'], location: 'Janakpuri, Delhi', bio: 'Experienced housekeeper with elder care and home cooking expertise.', rating: 4.6, total_reviews: 52, experience_years: 5, completion_rate: 97, availability: true, lat: 28.6210, lng: 77.0856, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-teal-400' },
  { id: 'w27', name: 'Mohammad Ansari', email: 'ansari@example.com', phone: '+91 98765 43236', category: 'Carpenter', services: ['Carpenter', 'Modular Kitchen', 'Wardrobe'], location: 'Faridabad Sector 15', bio: 'Specialized in modular kitchen and wardrobe design and installation.', rating: 4.7, total_reviews: 78, experience_years: 10, completion_rate: 95, availability: true, lat: 28.3761, lng: 77.3144, hourly_rate: 800, user_type: 'worker', avatar_color: 'bg-amber-500' },
  { id: 'w28', name: 'Lakshmi Devi', email: 'lakshmi@example.com', phone: '+91 98765 43237', category: 'Home Cleaning', services: ['Home Cleaning', 'Carpet Cleaning', 'Sofa Cleaning'], location: 'Paschim Vihar, Delhi', bio: 'Deep cleaning specialist for homes, carpets, and upholstery.', rating: 4.8, total_reviews: 68, experience_years: 4, completion_rate: 98, availability: true, lat: 28.6679, lng: 77.0882, hourly_rate: 380, user_type: 'worker', avatar_color: 'bg-purple-400' },
  { id: 'w29', name: 'Harish Chandra', email: 'harish@example.com', phone: '+91 98765 43238', category: 'Electrician', services: ['Electrician', 'Smart Home', 'Security Systems'], location: 'Green Park, Delhi', bio: 'Smart home automation and security system installation expert.', rating: 4.6, total_reviews: 42, experience_years: 7, completion_rate: 94, availability: true, lat: 28.5606, lng: 77.2047, hourly_rate: 750, user_type: 'worker', avatar_color: 'bg-blue-500' },
  { id: 'w30', name: 'Sunil Kumar', email: 'sunil@example.com', phone: '+91 98765 43239', category: 'Mason', services: ['Mason', 'Civil Work', 'Construction'], location: 'Alaknanda, Delhi', bio: 'Experienced mason for civil work, construction, and renovation projects.', rating: 4.3, total_reviews: 55, experience_years: 15, completion_rate: 90, availability: true, lat: 28.5359, lng: 77.2475, hourly_rate: 650, user_type: 'worker', avatar_color: 'bg-stone-500' },
  { id: 'w31', name: 'Rekha Sharma', email: 'rekha@example.com', phone: '+91 98765 43240', category: 'Appliance Repair', services: ['Appliance Repair', 'Microwave', 'Geyser'], location: 'Vasant Kunj, Delhi', bio: 'Home appliance repair for microwaves, geysers, and kitchen appliances.', rating: 4.5, total_reviews: 61, experience_years: 6, completion_rate: 93, availability: true, lat: 28.5140, lng: 77.1579, hourly_rate: 500, user_type: 'worker', avatar_color: 'bg-orange-400' },
  { id: 'w32', name: 'Vikram Singh', email: 'vikrams@example.com', phone: '+91 98765 43241', category: 'Driver Services', services: ['Driver Services', 'Corporate Transport', 'School Van'], location: 'Mehrauli, Delhi', bio: 'Professional driver for corporate transport and school van services.', rating: 4.4, total_reviews: 38, experience_years: 8, completion_rate: 92, availability: true, lat: 28.5243, lng: 77.1792, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-slate-500' },
  { id: 'w33', name: 'Amitabh Mishra', email: 'amitabh@example.com', phone: '+91 98765 43242', category: 'RO Water Purifier Service', services: ['RO Water Purifier Service', 'Water Filter', ' TDS'], location: 'Dilshad Garden, Delhi', bio: 'Water purifier specialist for all brands. TDS testing and filter replacement.', rating: 4.6, total_reviews: 35, experience_years: 4, completion_rate: 96, availability: true, lat: 28.6811, lng: 77.3159, hourly_rate: 420, user_type: 'worker', avatar_color: 'bg-cyan-400' },
  { id: 'w34', name: 'Nidhi Agarwal', email: 'nidhi@example.com', phone: '+91 98765 43243', category: 'Security Guard', services: ['Security Guard', 'Event Security', 'Bouncer'], location: 'MG Road, Gurgaon', bio: 'Trained security personnel for events, parties, and corporate security.', rating: 4.5, total_reviews: 29, experience_years: 6, completion_rate: 98, availability: true, lat: 28.4755, lng: 77.0278, hourly_rate: 350, user_type: 'worker', avatar_color: 'bg-gray-500' },
  { id: 'w35', name: 'Pawan Kumar', email: 'pawan@example.com', phone: '+91 98765 43244', category: 'Delivery Services', services: ['Delivery Services', 'Furniture Moving', 'Heavy'], location: 'Naraina, Delhi', bio: 'Heavy item delivery and furniture moving within Delhi NCR.', rating: 4.2, total_reviews: 41, experience_years: 3, completion_rate: 95, availability: true, lat: 28.6139, lng: 77.1471, hourly_rate: 300, user_type: 'worker', avatar_color: 'bg-yellow-600' },
  { id: 'w36', name: 'Seema Yadav', email: 'seema@example.com', phone: '+91 98765 43245', category: 'Painter', services: ['Painter', 'Waterproofing', 'Roof Repair'], location: 'Govindpuri, Delhi', bio: 'Painter and waterproofing specialist. Roof repair and texture finishing.', rating: 4.6, total_reviews: 58, experience_years: 8, completion_rate: 94, availability: true, lat: 28.5376, lng: 77.2679, hourly_rate: 580, user_type: 'worker', avatar_color: 'bg-violet-400' },
  { id: 'w37', name: 'Dinesh Patel', email: 'dinesh@example.com', phone: '+91 98765 43246', category: 'Plumber', services: ['Plumber', 'Sewage', 'Drainage'], location: 'Kirti Nagar, Delhi', bio: 'Expert in sewage cleaning, drainage repair, and pipe unclogging.', rating: 4.4, total_reviews: 76, experience_years: 9, completion_rate: 91, availability: true, lat: 28.6522, lng: 77.1316, hourly_rate: 520, user_type: 'worker', avatar_color: 'bg-blue-600' },
  { id: 'w38', name: 'Kamlesh Jain', email: 'kamlesh@example.com', phone: '+91 98765 43247', category: 'Computer/Laptop Repair', services: ['Computer/Laptop Repair', 'Printer', 'Scanner'], location: ' Nehru Place, Delhi', bio: 'IT solutions including printer, scanner, and all computer peripherals.', rating: 4.5, total_reviews: 67, experience_years: 7, completion_rate: 93, availability: true, lat: 28.5496, lng: 77.2529, hourly_rate: 520, user_type: 'worker', avatar_color: 'bg-indigo-500' },
  { id: 'w39', name: 'Pushpa Rani', email: 'pushpa@example.com', phone: '+91 98765 43248', category: 'Salon at Home', services: ['Salon at Home', 'Mehendi', 'Mehndi'], location: 'Madipur, Delhi', bio: 'Traditional and bridal mehendi artist. Body art and temporary tattoos.', rating: 4.8, total_reviews: 48, experience_years: 10, completion_rate: 99, availability: true, lat: 28.6725, lng: 77.1137, hourly_rate: 450, user_type: 'worker', avatar_color: 'bg-amber-400' },
  { id: 'w40', name: 'Yogesh Kumar', email: 'yogesh@example.com', phone: '+91 98765 43249', category: 'Washing Machine Repair', services: ['Washing Machine Repair', 'Dryer Repair'], location: 'Shalimar Bagh, Delhi', bio: 'Washing machine and clothes dryer repair specialist.', rating: 4.3, total_reviews: 44, experience_years: 5, completion_rate: 92, availability: true, lat: 28.7152, lng: 77.1528, hourly_rate: 420, user_type: 'worker', avatar_color: 'bg-sky-500' },
  { id: 'w41', name: 'Imran Siddiqui', email: 'imran@example.com', phone: '+91 98765 43250', category: 'Electrician', services: ['Electrician', 'Inverter Repair', 'UPS Installation'], location: 'Batla House, Delhi', bio: 'Expert electrician specializing in inverter and UPS systems for homes and offices.', rating: 4.7, total_reviews: 63, experience_years: 8, completion_rate: 96, availability: true, lat: 28.5653, lng: 77.2867, hourly_rate: 550, user_type: 'worker', avatar_color: 'bg-blue-600' },
  { id: 'w42', name: 'Shabana Begum', email: 'shabana@example.com', phone: '+91 98765 43251', category: 'Salon at Home', services: ['Salon at Home', 'Threading', 'Facial'], location: 'Zakir Nagar, Delhi', bio: 'Professional beautician offering threading, facials, and skin care treatments at home.', rating: 4.8, total_reviews: 55, experience_years: 7, completion_rate: 98, availability: true, lat: 28.5630, lng: 77.2820, hourly_rate: 500, user_type: 'worker', avatar_color: 'bg-rose-500' },
  { id: 'w43', name: 'Naveen Jha', email: 'naveen@example.com', phone: '+91 98765 43252', category: 'Plumber', services: ['Plumber', 'Water Tank Cleaning', 'Motor Repair'], location: 'Okhla Phase 1, Delhi', bio: 'Plumbing expert with specialization in overhead tank cleaning and motor pump repairs.', rating: 4.5, total_reviews: 71, experience_years: 9, completion_rate: 94, availability: true, lat: 28.5330, lng: 77.2710, hourly_rate: 480, user_type: 'worker', avatar_color: 'bg-cyan-600' },
  { id: 'w44', name: 'Aarti Chauhan', email: 'aarti@example.com', phone: '+91 98765 43253', category: 'Home Cleaning', services: ['Home Cleaning', 'Office Cleaning', 'Post-Construction Cleaning'], location: 'New Friends Colony, Delhi', bio: 'Deep cleaning specialist for post-construction, move-in, and office spaces.', rating: 4.6, total_reviews: 48, experience_years: 4, completion_rate: 97, availability: true, lat: 28.5640, lng: 77.2570, hourly_rate: 380, user_type: 'worker', avatar_color: 'bg-emerald-500' },
  { id: 'w45', name: 'Mohd Tariq', email: 'tariq@example.com', phone: '+91 98765 43254', category: 'Carpenter', services: ['Carpenter', 'Door Repair', 'Window Fitting'], location: 'Sukhdev Vihar, Delhi', bio: 'Skilled carpenter for door installation, window fitting, and wooden frame repairs.', rating: 4.4, total_reviews: 59, experience_years: 11, completion_rate: 93, availability: true, lat: 28.5560, lng: 77.2690, hourly_rate: 600, user_type: 'worker', avatar_color: 'bg-amber-600' },
  { id: 'w46', name: 'Geeta Rani', email: 'geeta@example.com', phone: '+91 98765 43255', category: 'Housekeeping', services: ['Housekeeping', 'Baby Sitting', 'Cooking'], location: 'Okhla Phase 2, Delhi', bio: 'Trained housekeeper offering babysitting, cooking, and household management services.', rating: 4.7, total_reviews: 41, experience_years: 6, completion_rate: 98, availability: true, lat: 28.5300, lng: 77.2750, hourly_rate: 350, user_type: 'worker', avatar_color: 'bg-pink-400' },
  { id: 'w47', name: 'Rajendra Prasad', email: 'rajendra@example.com', phone: '+91 98765 43256', category: 'AC Repair', services: ['AC Repair', 'Cooler Servicing', 'Heating Systems'], location: 'Gurgaon Sector 56', bio: 'HVAC technician for AC, desert cooler, and central heating system maintenance.', rating: 4.6, total_reviews: 82, experience_years: 10, completion_rate: 95, availability: true, lat: 28.4220, lng: 77.0400, hourly_rate: 650, user_type: 'worker', avatar_color: 'bg-sky-600' },
  { id: 'w48', name: 'Sakina Khatun', email: 'sakina@example.com', phone: '+91 98765 43257', category: 'Tailor Services', services: ['Tailor Services', 'Embroidery', 'Kurti Stitching'], location: 'Batla House, Delhi', bio: 'Expert tailor for ladies garments, embroidery, and traditional ethnic wear stitching.', rating: 4.8, total_reviews: 53, experience_years: 12, completion_rate: 99, availability: true, lat: 28.5660, lng: 77.2880, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-fuchsia-400' },
  { id: 'w49', name: 'Anil Rawat', email: 'anil@example.com', phone: '+91 98765 43258', category: 'Painter', services: ['Painter', 'POP Work', 'False Ceiling'], location: 'Noida Sector 18', bio: 'Professional painter with expertise in POP design, false ceiling, and gypsum work.', rating: 4.5, total_reviews: 66, experience_years: 8, completion_rate: 94, availability: true, lat: 28.5692, lng: 77.3217, hourly_rate: 620, user_type: 'worker', avatar_color: 'bg-violet-600' },
  { id: 'w50', name: 'Mumtaz Ali', email: 'mumtaz@example.com', phone: '+91 98765 43259', category: 'Mobile Repair', services: ['Mobile Repair', 'Chip Level Repair', 'Data Recovery'], location: 'Zakir Nagar, Delhi', bio: 'Advanced mobile repair including chip-level servicing and data recovery for all brands.', rating: 4.6, total_reviews: 87, experience_years: 6, completion_rate: 93, availability: true, lat: 28.5625, lng: 77.2835, hourly_rate: 450, user_type: 'worker', avatar_color: 'bg-indigo-600' },
  { id: 'w51', name: 'Sunanda Devi', email: 'sunanda@example.com', phone: '+91 98765 43260', category: 'Pest Control', services: ['Pest Control', 'Bed Bug Treatment', 'Cockroach Control'], location: 'New Friends Colony, Delhi', bio: 'Certified pest control professional with safe chemical-free options for families.', rating: 4.7, total_reviews: 39, experience_years: 5, completion_rate: 97, availability: true, lat: 28.5650, lng: 77.2580, hourly_rate: 480, user_type: 'worker', avatar_color: 'bg-lime-600' },
  { id: 'w52', name: 'Farhan Ahmed', email: 'farhan@example.com', phone: '+91 98765 43261', category: 'Computer/Laptop Repair', services: ['Computer/Laptop Repair', 'CCTV Installation', 'Networking'], location: 'Sukhdev Vihar, Delhi', bio: 'IT solutions expert for CCTV setup, networking, and computer hardware repair.', rating: 4.5, total_reviews: 57, experience_years: 7, completion_rate: 95, availability: true, lat: 28.5550, lng: 77.2700, hourly_rate: 580, user_type: 'worker', avatar_color: 'bg-gray-600' },
  { id: 'w53', name: 'Kamla Bai', email: 'kamla@example.com', phone: '+91 98765 43262', category: 'Housekeeping', services: ['Housekeeping', 'Ironing', 'Laundry'], location: 'Gurgaon Sector 14', bio: 'Experienced housekeeper providing ironing, laundry, and daily household cleaning.', rating: 4.3, total_reviews: 46, experience_years: 8, completion_rate: 91, availability: true, lat: 28.4680, lng: 77.0260, hourly_rate: 280, user_type: 'worker', avatar_color: 'bg-teal-500' },
  { id: 'w54', name: 'Bharat Singh', email: 'bharat@example.com', phone: '+91 98765 43263', category: 'Mason', services: ['Mason', 'Marble Polishing', 'Tile Cutting'], location: 'Noida Sector 44', bio: 'Master mason for marble flooring, tile cutting, and precision stone work installations.', rating: 4.6, total_reviews: 74, experience_years: 14, completion_rate: 96, availability: true, lat: 28.5780, lng: 77.3450, hourly_rate: 700, user_type: 'worker', avatar_color: 'bg-stone-600' },
  { id: 'w55', name: 'Zoya Khan', email: 'zoya@example.com', phone: '+91 98765 43264', category: 'Salon at Home', services: ['Salon at Home', 'Makeup Artist', 'Hair Spa'], location: 'Okhla, Delhi', bio: 'Professional makeup artist and hair spa specialist. Bridal, party, and casual looks.', rating: 4.9, total_reviews: 92, experience_years: 8, completion_rate: 99, availability: true, lat: 28.5310, lng: 77.2720, hourly_rate: 900, user_type: 'worker', avatar_color: 'bg-rose-400' },
]

export const dummyServices = [
  { id: 's1', title: 'Professional Home Cleaning', description: 'Complete home cleaning with eco-friendly products. Includes kitchen, bathroom, and all living areas. Deep cleaning available.', category: 'Home Cleaning', price: 1500, location: 'Connaught Place, Delhi', worker_id: 'w2', worker_name: 'Priya Singh', rating: 4.9, total_reviews: 89, is_active: true, createdAt: '2025-12-01T10:00:00Z', updatedAt: '2026-01-15T10:00:00Z' },
  { id: 's2', title: 'Plumbing & Pipe Repair', description: 'Expert plumbing services - leak repair, pipe installation, bathroom fitting, and drainage solutions. Emergency service available.', category: 'Plumber', price: 800, location: 'Lajpat Nagar, Delhi', worker_id: 'w1', worker_name: 'Rajesh Kumar', rating: 4.8, total_reviews: 124, is_active: true, createdAt: '2025-11-20T10:00:00Z', updatedAt: '2026-01-10T10:00:00Z' },
  { id: 's3', title: 'Electrical Wiring & Repair', description: 'Complete electrical solutions - wiring, switchboard installation, fan/light fitting, MCB and safety inspection.', category: 'Electrician', price: 1200, location: 'Karol Bagh, Delhi', worker_id: 'w3', worker_name: 'Amar Patel', rating: 4.7, total_reviews: 156, is_active: true, createdAt: '2025-11-15T10:00:00Z', updatedAt: '2026-01-05T10:00:00Z' },
  { id: 's4', title: 'Interior & Exterior Painting', description: 'Transform your space with professional painting. Texture painting, wall art, and expert color consultation included.', category: 'Painter', price: 2500, location: 'Rajouri Garden, Delhi', worker_id: 'w4', worker_name: 'Sunita Devi', rating: 4.6, total_reviews: 67, is_active: true, createdAt: '2025-12-10T10:00:00Z', updatedAt: '2026-01-20T10:00:00Z' },
  { id: 's5', title: 'Custom Furniture & Carpentry', description: 'Bespoke woodwork - custom furniture, cabinet installation, door repair, and wood polishing by skilled carpenters.', category: 'Carpenter', price: 3000, location: 'Dwarka, Delhi', worker_id: 'w5', worker_name: 'Vikram Choudhary', rating: 4.5, total_reviews: 98, is_active: true, createdAt: '2025-11-25T10:00:00Z', updatedAt: '2026-01-12T10:00:00Z' },
  { id: 's6', title: 'Housekeeping & Gardening', description: 'Professional housekeeping - lawn maintenance, indoor plant care, daily cleaning, and terrace garden setup.', category: 'Housekeeping', price: 1000, location: 'Hauz Khas, Delhi', worker_id: 'w6', worker_name: 'Meena Kumari', rating: 4.8, total_reviews: 45, is_active: true, createdAt: '2025-12-05T10:00:00Z', updatedAt: '2026-01-18T10:00:00Z' },
  { id: 's7', title: 'AC Installation & Repair', description: 'Split AC, window AC installation, gas refilling, compressor repair, and annual maintenance. All brands covered.', category: 'AC Repair', price: 1800, location: 'Saket, Delhi', worker_id: 'w7', worker_name: 'Arjun Reddy', rating: 4.7, total_reviews: 112, is_active: true, createdAt: '2025-12-08T10:00:00Z', updatedAt: '2026-01-22T10:00:00Z' },
  { id: 's8', title: 'Salon & Beauty at Home', description: 'Complete salon experience at your doorstep - haircut, facial, waxing, bridal makeup, and grooming packages.', category: 'Salon at Home', price: 1500, location: 'Khan Market, Delhi', worker_id: 'w8', worker_name: 'Fatima Khan', rating: 4.9, total_reviews: 78, is_active: true, createdAt: '2025-12-12T10:00:00Z', updatedAt: '2026-01-25T10:00:00Z' },
  { id: 's9', title: 'Masonry & Tile Work', description: 'Professional masonry - wall construction, tile fitting, plastering, waterproofing, and bathroom renovation.', category: 'Mason', price: 2000, location: 'Rohini, Delhi', worker_id: 'w9', worker_name: 'Suresh Yadav', rating: 4.4, total_reviews: 86, is_active: true, createdAt: '2025-12-15T10:00:00Z', updatedAt: '2026-01-28T10:00:00Z' },
  { id: 's10', title: 'Pest Control Treatment', description: 'Complete pest control - cockroach, termite, bed bug, mosquito, and rodent treatment. Safe for kids and pets.', category: 'Pest Control', price: 2500, location: 'Defence Colony, Delhi', worker_id: 'w10', worker_name: 'Kavitha Nair', rating: 4.6, total_reviews: 54, is_active: true, createdAt: '2025-12-18T10:00:00Z', updatedAt: '2026-02-01T10:00:00Z' },
  { id: 's11', title: 'Mobile Phone Repair', description: 'Screen replacement, battery change, charging port fix, software issues, and water damage repair. All brands.', category: 'Mobile Repair', price: 500, location: 'Chandni Chowk, Delhi', worker_id: 'w11', worker_name: 'Rohit Sharma', rating: 4.5, total_reviews: 132, is_active: true, createdAt: '2025-12-20T10:00:00Z', updatedAt: '2026-02-03T10:00:00Z' },
  { id: 's12', title: 'Laptop & Computer Repair', description: 'Laptop repair, OS installation, virus removal, data recovery, RAM/SSD upgrade, and networking setup.', category: 'Computer/Laptop Repair', price: 800, location: 'Noida Sector 62', worker_id: 'w12', worker_name: 'Deepak Mishra', rating: 4.7, total_reviews: 91, is_active: true, createdAt: '2025-12-22T10:00:00Z', updatedAt: '2026-02-05T10:00:00Z' },
  { id: 's13', title: 'Washing Machine Repair', description: 'Repair for all types - front load, top load, semi-automatic. Drum, motor, PCB, and drain pump servicing.', category: 'Washing Machine Repair', price: 700, location: 'Noida Sector 15', worker_id: 'w15', worker_name: 'Manoj Tiwari', rating: 4.4, total_reviews: 58, is_active: true, createdAt: '2025-12-25T10:00:00Z', updatedAt: '2026-02-08T10:00:00Z' },
  { id: 's14', title: 'RO Purifier Service', description: 'RO water purifier installation, filter change, membrane replacement, and annual maintenance contract.', category: 'RO Water Purifier Service', price: 600, location: 'Barakhamba Road, Delhi', worker_id: 'w16', worker_name: 'Sanjay Verma', rating: 4.5, total_reviews: 42, is_active: true, createdAt: '2025-12-28T10:00:00Z', updatedAt: '2026-02-10T10:00:00Z' },
  { id: 's15', title: 'Refrigerator Repair', description: 'Fridge not cooling? Gas refill, compressor, thermostat, and door gasket repair. Single and double door models.', category: 'Refrigerator Repair', price: 900, location: 'Saket, Delhi', worker_id: 'w7', worker_name: 'Arjun Reddy', rating: 4.6, total_reviews: 73, is_active: true, createdAt: '2026-01-02T10:00:00Z', updatedAt: '2026-02-12T10:00:00Z' },
  { id: 's16', title: 'Driver on Demand', description: 'Professional driver for city rides, airport transfers, outstation trips, and weddings. Commercial license holder.', category: 'Driver Services', price: 1200, location: 'Rajiv Chowk, Delhi', worker_id: 'w13', worker_name: 'Ramesh Gupta', rating: 4.3, total_reviews: 64, is_active: true, createdAt: '2026-01-05T10:00:00Z', updatedAt: '2026-02-15T10:00:00Z' },
  { id: 's17', title: 'Tailoring & Alterations', description: 'Expert stitching - blouse, kurta, suits, alterations, hemming, and custom outfits. Pickup & delivery available.', category: 'Tailor Services', price: 400, location: 'Chittaranjan Park, Delhi', worker_id: 'w14', worker_name: 'Anita Joshi', rating: 4.8, total_reviews: 76, is_active: true, createdAt: '2026-01-08T10:00:00Z', updatedAt: '2026-02-18T10:00:00Z' },
  { id: 's18', title: 'Security Guard Service', description: 'Trained security personnel for events, offices, and residential complexes. Day and night shifts available.', category: 'Security Guard', price: 800, location: 'Gurgaon Cyber City', worker_id: 'w17', worker_name: 'Prakash Raj', rating: 4.6, total_reviews: 38, is_active: true, createdAt: '2026-01-10T10:00:00Z', updatedAt: '2026-02-20T10:00:00Z' },
  { id: 's19', title: 'Same-Day Delivery', description: 'Reliable same-day pickup and delivery within Delhi NCR. Documents, parcels, and fragile items handled with care.', category: 'Delivery Services', price: 200, location: 'Golf Course Road, Gurgaon', worker_id: 'w18', worker_name: 'Pooja Bansal', rating: 4.3, total_reviews: 49, is_active: true, createdAt: '2026-01-12T10:00:00Z', updatedAt: '2026-02-22T10:00:00Z' },
  { id: 's20', title: 'Appliance Installation', description: 'Installation of TV, geyser, chimney, microwave wall mount, and ceiling fan. Includes wiring and testing.', category: 'Appliance Repair', price: 600, location: 'Karol Bagh, Delhi', worker_id: 'w3', worker_name: 'Amar Patel', rating: 4.5, total_reviews: 63, is_active: true, createdAt: '2026-01-15T10:00:00Z', updatedAt: '2026-02-25T10:00:00Z' },
  { id: 's21', title: 'Smart Home Setup', description: 'Complete smart home automation - lights, security cameras, door locks, and voice assistants installation.', category: 'Electrician', price: 3500, location: 'Green Park, Delhi', worker_id: 'w29', worker_name: 'Harish Chandra', rating: 4.6, total_reviews: 42, is_active: true, createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-28T10:00:00Z' },
  { id: 's22', title: 'Modular Kitchen Installation', description: 'Custom modular kitchen design and installation. Premium finishes and modern layouts.', category: 'Carpenter', price: 25000, location: 'Faridabad Sector 15', worker_id: 'w27', worker_name: 'Mohammad Ansari', rating: 4.7, total_reviews: 78, is_active: true, createdAt: '2026-02-05T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z' },
  { id: 's23', title: 'Carpet & Sofa Cleaning', description: 'Professional deep cleaning for carpets, sofas, and mattresses. Stain removal and sanitization included.', category: 'Home Cleaning', price: 1200, location: 'Paschim Vihar, Delhi', worker_id: 'w28', worker_name: 'Lakshmi Devi', rating: 4.8, total_reviews: 68, is_active: true, createdAt: '2026-02-10T10:00:00Z', updatedAt: '2026-03-05T10:00:00Z' },
  { id: 's24', title: 'Bridal Makeup Package', description: 'Complete bridal makeup with hairstyling, draping, and mehendi coordination. Premium products used.', category: 'Salon at Home', price: 5000, location: 'Greater Kailash, Delhi', worker_id: 'w22', worker_name: 'Preeti Gupta', rating: 4.9, total_reviews: 112, is_active: true, createdAt: '2026-02-15T10:00:00Z', updatedAt: '2026-03-10T10:00:00Z' },
  { id: 's25', title: 'Generator Repair & Service', description: 'Expert generator servicing, repair, and annual maintenance. Both petrol and diesel generators.', category: 'Electrician', price: 2000, location: 'Paharganj, Delhi', worker_id: 'w19', worker_name: 'Vijay Malhotra', rating: 4.6, total_reviews: 72, is_active: true, createdAt: '2026-02-20T10:00:00Z', updatedAt: '2026-03-15T10:00:00Z' },
]

export const dummyJobs = [
  { id: 'j1', title: 'Frontend Developer', company: 'TechVista Solutions', location: 'Remote', type: 'Full-time', employment_type: 'full_time', salary_min: 360000, salary_max: 360000, description: 'We are looking for a skilled Frontend Developer to build modern web applications using React.js and Tailwind CSS. The ideal candidate will be responsible for translating design wireframes into high-quality code and optimizing components for maximum performance.', skills_required: ['React', 'JavaScript', 'Tailwind CSS', 'Redux'], experience_required: '1–3 years', responsibilities: ['Develop new user-facing features', 'Build reusable code and libraries', 'Ensure technical feasibility of UI/UX designs', 'Optimize application for maximum speed'], perks: ['Flexible hours', 'Health Insurance', 'Remote Work', '5 Days a week'], about_company: 'TechVista Solutions is a leading software development agency specializing in SaaS platforms.', is_active: true, employer_id: 'e1', posted_by: 'TechVista HR', createdAt: new Date(Date.now() - 2 * 86400000).toISOString(), updatedAt: new Date(Date.now() - 2 * 86400000).toISOString() },
  { id: 'j2', title: 'Backend Developer', company: 'DataFlow Inc.', location: 'Noida Sector 62', type: 'Full-time', employment_type: 'full_time', salary_min: 480000, salary_max: 600000, description: 'DataFlow Inc is seeking an experienced Backend Developer to design, build, and maintain efficient, reusable, and reliable Node.js and Python code. You will be a part of a fast-paced environment supporting scaling infrastructure.', skills_required: ['Node.js', 'Python', 'PostgreSQL', 'Docker'], experience_required: '2–5 years', responsibilities: ['Integration of user-facing elements', 'Build efficient, testable backend logic', 'Solve complex performance problems', 'Database schema design'], perks: ['Performance Bonus', 'Stock Options', 'Health Insurance', 'Free Meals'], about_company: 'DataFlow Inc. builds high-capacity data pipelines and AI solutions for fortune 500 companies.', is_active: true, employer_id: 'e3', posted_by: 'DataFlow HR', createdAt: new Date(Date.now() - 4 * 86400000).toISOString(), updatedAt: new Date(Date.now() - 4 * 86400000).toISOString() },
  { id: 'j3', title: 'UI Designer', company: 'DesignCraft Studio', location: 'Hauz Khas, Delhi', type: 'Internship', employment_type: 'internship', salary_min: 240000, salary_max: 240000, description: 'We are looking for an ambitious UI Design Intern who is passionate about creating intuitive and visually appealing digital experiences. You will collaborate closely with our senior designers product teams.', skills_required: ['Figma', 'Adobe XD', 'Prototyping', 'Typography'], experience_required: 'Fresher', responsibilities: ['Assist in designing user interfaces', 'Create wireframes and user flows', 'Conduct basic user research', 'Adhere to style standards'], perks: ['Certificate', 'Letter of Recommendation', 'Pre-placement Offer', 'Informal Dress Code'], about_company: 'DesignCraft Studio is an award-winning creative agency based in the heart of Delhi.', is_active: true, employer_id: 'e2', posted_by: 'DesignCraft HR', createdAt: new Date(Date.now() - 1 * 86400000).toISOString(), updatedAt: new Date(Date.now() - 1 * 86400000).toISOString() },
  { id: 'j4', title: 'Digital Marketing Executive', company: 'GrowthPulse Media', location: 'Gurgaon Cyber City', type: 'Full-time', employment_type: 'full_time', salary_min: 400000, salary_max: 550000, description: 'Drive our digital presence through innovative SEO, SEM, and Social Media strategies. You will manage daily campaigns and report directly to the Marketing Director.', skills_required: ['SEO', 'Google Ads', 'Social Media', 'Google Analytics'], experience_required: '1–2 years', responsibilities: ['Plan and execute web campaigns', 'Maintain social media presence', 'Measure and report performance of all campaigns', 'Identify trends and insights'], perks: ['Flexible working hours', 'Performance Bonus', 'Health Insurance'], about_company: 'GrowthPulse Media is a leading digital marketing agency helping D2C brands scale rapidly.', is_active: true, employer_id: 'e4', posted_by: 'GrowthPulse HR', createdAt: new Date(Date.now() - 5 * 86400000).toISOString(), updatedAt: new Date(Date.now() - 5 * 86400000).toISOString() },
  { id: 'j5', title: 'React Native Developer', company: 'MobileFirst Apps', location: 'Remote', type: 'Contract', employment_type: 'contract', salary_min: 800000, salary_max: 1200000, description: 'We need an experienced React Native developer to build a high-performance cross-platform application for our logistics tracking ecosystem.', skills_required: ['React Native', 'TypeScript', 'Redux', 'REST APIs'], experience_required: '3–5 years', responsibilities: ['Build robust mobile applications', 'Integrate native APIs', 'Troubleshoot and debug', 'Maintain code quality'], perks: ['100% Remote', 'Flexible schedule', 'Project-based bonus'], about_company: 'MobileFirst Apps builds enterprise-grade mobile solutions for modern startups.', is_active: true, employer_id: 'e5', posted_by: 'MobileFirst HR', createdAt: new Date(Date.now() - 10 * 86400000).toISOString(), updatedAt: new Date(Date.now() - 10 * 86400000).toISOString() }
]

export const dummyGigs = [
  { id: 'g1', title: 'Build a Website', description: 'We need a fully responsive, 5-page corporate website built from scratch using React or Next.js. Must be highly optimized for SEO and fast loading.', budget: 5000, category: 'Web Development', services: ['React', 'Next.js', 'Tailwind CSS', 'SEO'], status: 'open', client_details: { name: 'Raj Kumar', rating: 4.8, jobs_posted: 12, member_since: '2023' }, duration: '14 days', deadline: new Date(Date.now() + 14 * 86400000).toISOString(), employer_id: 'e1', location: 'Remote', createdAt: new Date(Date.now() - 1 * 86400000).toISOString(), updatedAt: new Date(Date.now() - 1 * 86400000).toISOString() },
  { id: 'g2', title: 'Mobile App UI Design', description: 'Looking for a talented UI designer to design 10 screens for a food delivery mobile application. I have basic wireframes ready, just need polished designs.', budget: 3000, category: 'UI/UX Design', services: ['Figma', 'UI Design', 'Mobile App Design', 'Wireframing'], status: 'open', client_details: { name: 'Anita Singh', rating: 4.5, jobs_posted: 3, member_since: '2024' }, duration: '7 days', deadline: new Date(Date.now() + 7 * 86400000).toISOString(), employer_id: 'e2', location: 'Remote', createdAt: new Date(Date.now() - 3 * 86400000).toISOString(), updatedAt: new Date(Date.now() - 3 * 86400000).toISOString() },
  { id: 'g3', title: 'SEO Optimization', description: 'Perform a complete SEO audit of my WordPress e-commerce store. Fix on-page issues, optimize meta tags, and provide a backlink building strategy.', budget: 2000, category: 'Digital Marketing', services: ['SEO', 'WordPress', 'Google Analytics', 'Ahrefs'], status: 'open', client_details: { name: 'Karan Sharma', rating: 5.0, jobs_posted: 24, member_since: '2022' }, duration: '5 days', deadline: new Date(Date.now() + 5 * 86400000).toISOString(), employer_id: 'e3', location: 'Remote', createdAt: new Date(Date.now() - 2 * 86400000).toISOString(), updatedAt: new Date(Date.now() - 2 * 86400000).toISOString() },
  { id: 'g4', title: 'Write 10 SEO Articles', description: 'Seeking a freelance content writer to write 10 well-researched, SEO-optimized articles (1000 words each) in the B2B SaaS niche.', budget: 8000, category: 'Writing', services: ['Content Writing', 'SEO Copywriting', 'B2B Writing', 'Research'], status: 'open', client_details: { name: 'Megha Gupta', rating: 4.9, jobs_posted: 8, member_since: '2023' }, duration: '20 days', deadline: new Date(Date.now() + 20 * 86400000).toISOString(), employer_id: 'e4', location: 'Remote', createdAt: new Date(Date.now() - 5 * 86400000).toISOString(), updatedAt: new Date(Date.now() - 5 * 86400000).toISOString() },
  { id: 'g5', title: 'Fix React Native Bug', description: 'I have a crash occurring on iOS devices during the login flow. I need an experienced React Native developer to debug and fix it quickly.', budget: 1500, category: 'Mobile Development', services: ['React Native', 'iOS', 'Debugging', 'JavaScript'], status: 'open', client_details: { name: 'Vikram Joshi', rating: 4.2, jobs_posted: 1, member_since: '2025' }, duration: '2 days', deadline: new Date(Date.now() + 2 * 86400000).toISOString(), employer_id: 'e5', location: 'Remote', createdAt: new Date(Date.now() - 0.5 * 86400000).toISOString(), updatedAt: new Date(Date.now() - 0.5 * 86400000).toISOString() }
]

export const dummyReviews = [
  { id: 'r1', booking_id: 'b1', service_id: 's1', customer_id: 'c1', worker_id: 'w2', customer_name: 'Priya Sharma', service_title: 'Professional Home Cleaning', service_type: 'Home Cleaning', rating: 5, comment: 'Absolutely spotless! Priya did an amazing job with the deep cleaning. My apartment looks brand new. Highly recommended!', tags: ['Professional', 'On Time', 'Great Value'], createdAt: '2026-01-18T10:00:00Z' },
  { id: 'r2', booking_id: 'b2', service_id: 's2', customer_id: 'c2', worker_id: 'w1', customer_name: 'Rahul Mehta', service_title: 'Plumbing & Pipe Repair', service_type: 'Plumber', rating: 5, comment: 'Rajesh fixed a major leak in under an hour. Very professional and explained everything clearly. Fair pricing too.', tags: ['Expert', 'Quick Service'], createdAt: '2026-01-16T10:00:00Z' },
  { id: 'r3', booking_id: 'b3', service_id: 's3', customer_id: 'c3', worker_id: 'w3', customer_name: 'Anita Desai', service_title: 'Electrical Wiring & Repair', service_type: 'Electrician', rating: 5, comment: 'Got my entire house rewired. Amar and his team were incredibly thorough and safety-conscious. Excellent work!', tags: ['Professional', 'Safety First', 'Thorough'], createdAt: '2026-01-14T10:00:00Z' },
  { id: 'r4', booking_id: 'b4', service_id: 's4', customer_id: 'c4', worker_id: 'w4', customer_name: 'Deepak Verma', service_title: 'Interior & Exterior Painting', service_type: 'Painter', rating: 4, comment: 'Good painting work overall. The texture finish on the accent wall looks beautiful. Took a bit longer than expected but worth it.', tags: ['Good Quality', 'Creative'], createdAt: '2026-01-12T10:00:00Z' },
  { id: 'r5', booking_id: 'b5', service_id: 's5', customer_id: 'c5', worker_id: 'w5', customer_name: 'Sneha Iyer', service_title: 'Custom Furniture & Carpentry', service_type: 'Carpenter', rating: 5, comment: 'Vikram built a custom bookshelf and study table for my home office. The craftsmanship is outstanding. Will definitely hire again.', tags: ['Skilled', 'Creative', 'Professional'], createdAt: '2026-01-10T10:00:00Z' },
  { id: 'r6', booking_id: 'b6', service_id: 's6', customer_id: 'c6', worker_id: 'w6', customer_name: 'Amit Tiwari', service_title: 'Housekeeping & Gardening', service_type: 'Housekeeping', rating: 5, comment: 'My terrace garden looks magical! Meena has a great eye for design and chose the perfect plants for the space.', tags: ['Creative', 'Great Value', 'On Time'], createdAt: '2026-01-08T10:00:00Z' },
  { id: 'r7', booking_id: 'b7', service_id: 's7', customer_id: 'c7', worker_id: 'w7', customer_name: 'Nisha Kapoor', service_title: 'AC Installation & Repair', service_type: 'AC Repair', rating: 5, comment: 'Arjun was extremely knowledgeable. He diagnosed the AC issue quickly and the repair cost was very reasonable. Cooling is perfect now!', tags: ['Expert', 'Affordable', 'Quick Service'], createdAt: '2026-01-06T10:00:00Z' },
  { id: 'r8', booking_id: 'b8', service_id: 's8', customer_id: 'c8', worker_id: 'w8', customer_name: 'Meera Jain', service_title: 'Salon & Beauty at Home', service_type: 'Salon at Home', rating: 5, comment: 'Fatima did my bridal makeup and it was absolutely stunning! She is so talented and patient. All my guests were impressed.', tags: ['Talented', 'Patient', 'Professional'], createdAt: '2026-01-04T10:00:00Z' },
]

export const dummyBookings = [
  { id: 'bk1', service_title: 'Professional Home Cleaning', customer_name: 'Priya Sharma', worker_name: 'Priya Singh', customer_id: 'c1', worker_id: 'w2', booking_date: '2026-01-20', time_slot: '9:00 AM - 11:00 AM', amount: 1500, status: 'completed', payment_status: 'paid', address: 'B-12, Connaught Place, New Delhi', createdAt: '2026-01-18T10:00:00Z' },
  { id: 'bk2', service_title: 'Plumbing & Pipe Repair', customer_name: 'Rahul Mehta', worker_name: 'Rajesh Kumar', customer_id: 'c2', worker_id: 'w1', booking_date: '2026-01-22', time_slot: '11:00 AM - 1:00 PM', amount: 800, status: 'completed', payment_status: 'paid', address: '45, Lajpat Nagar II, New Delhi', createdAt: '2026-01-20T10:00:00Z' },
  { id: 'bk3', service_title: 'AC Installation & Repair', customer_name: 'Nisha Kapoor', worker_name: 'Arjun Reddy', customer_id: 'c7', worker_id: 'w7', booking_date: '2026-01-25', time_slot: '2:00 PM - 4:00 PM', amount: 1800, status: 'accepted', payment_status: 'pending', address: 'C-88, Saket, New Delhi', createdAt: '2026-01-22T10:00:00Z' },
  { id: 'bk4', service_title: 'Salon & Beauty at Home', customer_name: 'Meera Jain', worker_name: 'Fatima Khan', customer_id: 'c8', worker_id: 'w8', booking_date: '2026-01-28', time_slot: '9:00 AM - 11:00 AM', amount: 1500, status: 'on_the_way', payment_status: 'paid', address: '23, Khan Market, New Delhi', createdAt: '2026-01-25T10:00:00Z' },
  { id: 'bk5', service_title: 'Pest Control Treatment', customer_name: 'Deepak Verma', worker_name: 'Kavitha Nair', customer_id: 'c4', worker_id: 'w10', booking_date: '2026-02-01', time_slot: '11:00 AM - 1:00 PM', amount: 2500, status: 'requested', payment_status: 'pending', address: 'A-67, Defence Colony, New Delhi', createdAt: '2026-01-28T10:00:00Z' },
  { id: 'bk6', service_title: 'Mobile Phone Repair', customer_name: 'Sneha Iyer', worker_name: 'Rohit Sharma', customer_id: 'c5', worker_id: 'w11', booking_date: '2026-02-03', time_slot: '2:00 PM - 4:00 PM', amount: 500, status: 'cancelled', payment_status: 'refunded', address: '34, Chandni Chowk, Old Delhi', createdAt: '2026-01-30T10:00:00Z' },
]

export const dummyUsers = [
  { id: 'c1', name: 'Priya Sharma', email: 'priya.sharma@example.com', user_type: 'customer', location: 'Connaught Place, Delhi', phone: '+91 91234 56701', suspended: false, createdAt: '2025-11-01T10:00:00Z' },
  { id: 'c2', name: 'Rahul Mehta', email: 'rahul.mehta@example.com', user_type: 'customer', location: 'Lajpat Nagar, Delhi', phone: '+91 91234 56702', suspended: false, createdAt: '2025-11-05T10:00:00Z' },
  { id: 'c3', name: 'Anita Desai', email: 'anita.desai@example.com', user_type: 'customer', location: 'Karol Bagh, Delhi', phone: '+91 91234 56703', suspended: false, createdAt: '2025-11-10T10:00:00Z' },
  { id: 'c4', name: 'Deepak Verma', email: 'deepak.verma@example.com', user_type: 'customer', location: 'Defence Colony, Delhi', phone: '+91 91234 56704', suspended: false, createdAt: '2025-11-15T10:00:00Z' },
  { id: 'c5', name: 'Sneha Iyer', email: 'sneha.iyer@example.com', user_type: 'customer', location: 'Dwarka, Delhi', phone: '+91 91234 56705', suspended: false, createdAt: '2025-11-20T10:00:00Z' },
  { id: 'w1', name: 'Rajesh Kumar', email: 'rajesh@example.com', user_type: 'worker', location: 'Lajpat Nagar, Delhi', phone: '+91 98765 43210', suspended: false, createdAt: '2025-10-01T10:00:00Z' },
  { id: 'w2', name: 'Priya Singh', email: 'priya@example.com', user_type: 'worker', location: 'Connaught Place, Delhi', phone: '+91 98765 43211', suspended: false, createdAt: '2025-10-05T10:00:00Z' },
  { id: 'w3', name: 'Amar Patel', email: 'amar@example.com', user_type: 'worker', location: 'Karol Bagh, Delhi', phone: '+91 98765 43212', suspended: false, createdAt: '2025-10-10T10:00:00Z' },
  { id: 'e1', name: 'TechVista HR', email: 'hr@techvista.com', user_type: 'employer', location: 'Connaught Place, Delhi', phone: '+91 11 4000 1001', suspended: false, createdAt: '2025-09-01T10:00:00Z' },
  { id: 'e2', name: 'DesignCraft HR', email: 'hr@designcraft.com', user_type: 'employer', location: 'Hauz Khas, Delhi', phone: '+91 11 4000 1002', suspended: false, createdAt: '2025-09-05T10:00:00Z' },
]

export const TIME_SLOTS = [
  { id: 'slot-1', label: '9:00 AM - 11:00 AM', value: '9:00 AM - 11:00 AM' },
  { id: 'slot-2', label: '11:00 AM - 1:00 PM', value: '11:00 AM - 1:00 PM' },
  { id: 'slot-3', label: '2:00 PM - 4:00 PM', value: '2:00 PM - 4:00 PM' },
]

export const BOOKING_STATUSES = [
  { key: 'requested', label: 'Requested', color: 'bg-yellow-100 text-yellow-800' },
  { key: 'accepted', label: 'Accepted', color: 'bg-blue-100 text-blue-800' },
  { key: 'on_the_way', label: 'On the Way', color: 'bg-indigo-100 text-indigo-800' },
  { key: 'completed', label: 'Completed', color: 'bg-green-100 text-green-800' },
  { key: 'reviewed', label: 'Reviewed', color: 'bg-emerald-100 text-emerald-800' },
  { key: 'cancelled', label: 'Cancelled', color: 'bg-red-100 text-red-800' },
]

export function calculateWorkerScore(worker, maxDistance = 15) {
  const rating = worker.rating || 0
  const experience = worker.experience_years || 0
  const distance = worker.distance || maxDistance
  const completionRate = worker.completion_rate || 100

  const ratingScore = (rating / 5.0) * 0.35 * 100
  const experienceScore = Math.min(experience / 10.0, 1.0) * 0.25 * 100
  const distanceScore = (1 - Math.min(distance / maxDistance, 1.0)) * 0.20 * 100
  const completionScore = (completionRate / 100.0) * 0.20 * 100

  return Math.round((ratingScore + experienceScore + distanceScore + completionScore) * 100) / 100
}

export function formatCurrencyINR(amount) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

export function formatSalaryRange(min, max) {
  const fmt = v => {
    if (v >= 100000) return `${(v / 100000).toFixed(v % 100000 === 0 ? 0 : 1)}L`
    if (v >= 1000) return `${(v / 1000).toFixed(0)}K`
    return `${v}`
  }
  return `${fmt(min)} - ${fmt(max)} /yr`
}
